### ISSUE TITLE
Warning on Mac OS X 10.11.6 - Macbook Pro Retina

### ISSUE THREAD

**Issue by dyorgio** [kwhat/jnativehook#110]
Nice lib!

Every time than I use this lib a warning appears in my console:

```
ago 02, 2016 12:56:09 PM java.lang.ClassLoader$NativeLibrary load
WARNING: jni_SetProperties [146]: Invalid result returned from hook_get_pointer_acceleration_threshold()!
```

About Retina Display support:

Mouse motion events aren't using pixels coords, some pixel motions are been ignored because that.

**Comment by kwhat** [comment]
Thanks.  That warning is probably because mouseDriverMaxSpeed is not set on your system.  Apple does a really shitty job exposing mouse acceleration and other system properties.  I don't suspect that is the reason your having pixel to resolution issues.  Let me know how you discovered the problem and how I can test and duplicate it.  Thanks!

**Comment by dyorgio** [comment]
Hi, tas for rapid reply! :)

I found that before El Capitain (10.11) the property was:
`defaults read com.apple.universalaccess mouseDriverMaxSpeed`
like you said (values range 1-32 (slow-fast)).

But now I found it on:
`defaults read NSGlobalDomain com.apple.mouse.scaling`
values appears to be between 0.0-3.0 (slow-fast)

**Comment by dyorgio** [comment]
Moved to: [https://github.com/kwhat/libuiohook/issues/37](https://github.com/kwhat/libuiohook/issues/37)
