### ISSUE TITLE
Solaris x86 library

### ISSUE THREAD

**Issue by caschaef** [kwhat/jnativehook#115]
Hi,

I was trying to use JNativeHook on a Solaris x86 and am receiving an error indicating "Unable to extract the native library /org/jnativehook/lib/solaris/x86_64/libJNativeHook.so ". The documentation indicates "The JNativeHook library ships with all the supported native libraries included in the jar file" however, looking into the downloaded jar there is no library just as the error indicates. The source appears to have hooks for Solaris x86. Is it not a supported?

Thanks
Cindy

**Comment by kwhat** [comment]
Hi, 

There is no technical reason it wont run on Solaris, however, it is not currently a supported platform.  I never added support because I didn't think anyone used Solaris.  There is no technical reason the code won't compile on your platform, and the linux binary included may even run on modern versions of Solaris.  You can test this by extracting /org/jnativehook/lib/linux/x86_64/libJNativeHook.so from the JAR, and then just add it to the java.library.path property.  There are countless articles on the internet on how to use that property.  If extraction does work, please let me know so I can patch the library locator. If it does not work, I will try and cross compile it for you.

**Comment by caschaef** [comment]
Hi,
Thanks so much for the quick reply. I will try extracting the Linux library and see if that works. I will let you know the results.

Thanks
Cindy

**Comment by caschaef** [comment]
Hi,
I am still not able to run my application. I extracted the Linux .so and added it's path to the java library path. My classpath still needs to reference the JNativeHook jar or I get an error indicating my main class cannot be found. With the jar in the classpath, the DefaultLibraryLocator is still being called and still looking for the solaris .so. Is there some step I am missing?

Thanks
Cindy

**Comment by caschaef** [comment]
This is basically what I did:
- extracted the .so and placed it in /h/Test/bin. 
- copied the JNativeHook jar file to /h/Test/bin.
- copied my compiled class to /h/Test/bin.
- updated my run script to:
        export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/h/Test/bin
        java -classpath /h/Test/bin:/h/Test/bin/jnativehook-2.0.2.jar myClass

myClass implements NativeMouseInputListener

**Comment by caschaef** [comment]
Hello,

I have tried multiple ways to set the java.library.path to the extracted libJNativeHook.so path but the code seems to not be able to find it. In all cases, the DefaultLibraryLocator.getLibraries method is still called and looks for /org/jnativehook/lib/solaris/x86_64/libJNativeHook.so

I tried add the –Djava.library.path to the command line. I also tried copying the extracted library to multiple location specified by the LD_LIBRARY_PATH environment variable, as well as updating the LD_LIBRARY_PATH to include the path to the library. All seem to be ignored.

Any ideas? Is there possibly something I am missing?

Thank you
Cindy Schaeffer

**Comment by caschaef** [comment]
Hello,

I have also tried to compile the source on our Solaris build machine. I am unable to build because our build machine does not have access to the internet and the build is trying to download libuiohook/archive/1.0.zip from https://github.com/kwhat. When I go to github and look for the archive directory, I am unable to find it. Can you please specify where it is located?

Thank you
Cindy

**Comment by kwhat** [comment]
Hi Cindy,

So you should be able to set –Djava.library.path=/tmp and then put libJNativeHook.so in that location. That should cause the DefaultLibraryLocator to load that file instead of the internal jar.  

As far as compiling goes, grab a copy of https://github.com/kwhat/libuiohook/tree/master and put it in [src/libuiohook](https://github.com/kwhat/jnativehook/tree/master/src) which wasn't included in the src zip because its a git remote repo.  The more stable option would be to use the 2.0.3 release from https://github.com/kwhat/jnativehook/releases, note that the JNativeHook-2.0.3.zip zip includes both binaries and the complete src.  Just make sure you run `ant distclean` before compiling.

You will also need the ant dependency for JNITasks v0.2 ant dependency.  If you haven't already, download it here: https://github.com/kwhat/jnitasks/releases, then place the jar in the project root.

Best,
Alex
