### ISSUE TITLE
Question: Multiple HID Input Devices

### ISSUE THREAD

**Issue by JHa13y** [kwhat/jnativehook#118]
Is there any planned capability, (or how hard would it be to add) to attach which device ID produced a keyboard event?  I'm working on an application that requires multiple keyboards to be differentiated and this solution is already 90% of the way there.

**Comment by kwhat** [comment]
Hi,

There is currently no way to detect the keyboard source due to where the hook operates which is really an OS level restriction.  For this library we basically tap into the OS keyboard event delivery mechanism after input events recieved from the individual devices are recieved and queued for application delivery.    What you, and several others, need is an HID java library.  Some exist, but last I checked they were less than stellar.  The issue with accepting HID events is that you cannot do language translation against those events so key typed events are out of the question.  There just isn't a way to convert HID codes to key codes at the OS level that I am aware of.  If you don't need key typed events or modifier masks then we could build a new project with something like https://msdn.microsoft.com/en-us/library/ms645546(v=vs.85).aspx

**Comment by faermanj** [comment]
Thanks for the clarification @kwhat, i am searching for a solution to this exact problem, trying to get a macro pad running on linux...
