### ISSUE TITLE
What is the correct way to post a Unicode character?

### ISSUE THREAD

**Issue by satyagraha** [kwhat/jnativehook#134]
FYI OS = Win7-64, release = 2.0.3.

 I'd like to post a Unicode character from the higher reaches of the Unicode space (http://unicode-table.com/en/#latin-1-supplement) . What is the correct way to do this using `jnativehook`? I've tried posting using `NATIVE_KEY_TYPED` but the event is rejected, presumably as per: https://github.com/kwhat/jnativehook/blob/master/src/java/org/jnativehook/GlobalScreen.java#L468 
Ideas?

**Comment by kwhat** [comment]
Key typed events are ignored because there is no way to determine what key combination produces that particular Unicode char at the native OS.  You would need to produce the key down and key up event with the correct modifiers for that Unicode key. 

https://github.com/kwhat/jnativehook/blob/master/src/jni/org_jnativehook_GlobalScreen.c#L134
https://github.com/kwhat/libuiohook/blob/fc7a252f729e98c55a3b4c8fe876ca156f040a68/src/windows/post_event.c#L272

**Comment by kwhat** [comment]
So, I have been thinking about this issue, as well as issues 132 and [136](https://github.com/kwhat/jnativehook/issues/136).  These are all really all coming from the same issue, which is if this library is providing scancodes or virtual key codes.  That was a hard question to answer at the beginning of this project, but I think that as this library begins to gain traction it has become clear that it should be providing virtual keycodes and not scancodes.  I will be releasing version 2.1 as soon as I can figure out how to build for arm7 and then I will be addressing these issues in version 3.0 by moving towards a virtual keycode system similar to what java currently does.  I am not sure when that release will be ready, but it wouldn't be that hard to implement at this point.  I will keep these tickets updated.

**Comment by marcelof01** [comment]
Any updates on this ticket?

**Comment by kwhat** [comment]
I don't think this will ever be supported.  You would need to post the keys required to generate the Unicode desired because there is no way to put unicode directly into the OS via an event.
