### ISSUE TITLE
How can you unregister the ConsumeEvent / VoidDispatchService

### ISSUE THREAD

**Issue by blizzardengle** [kwhat/jnativehook#142]
I know this feature is still unsupported but it's working great in all of my tests so far except for allowing the normal `GlobalScreen.unregisterNativeHook();` to work. For example in my application I have left in the code that the ESC key should unregister everything and shut down like so:

```
try {
    GlobalScreen.unregisterNativeHook();
} catch (NativeHookException ex) {
    /* Catch nothing */
}
```
Since I have added the `private class VoidDispatchService extends AbstractExecutorService { ... }` into the GlobalKeyListener.java I am attaching it to my application like so:
```
GlobalScreen.setEventDispatcher(new VoidDispatchService());
```
What I need to do though somehow is stop the `VoidDispatchService` from running or unregister it otherwise it prevents `GlobalScreen.unregisterNativeHook();` from running. It will completely get ignored and keep running the listeners.

**Comment by kwhat** [comment]
You are experiencing a deadlock because you are stopping the hook from within the hook ;)  You need to signal the GlobalScreen.unregisterNativeHook() from a different thread.  A quick fix would be to use something like the following to cheat a little

```
  SwingUtilities.invokeLater(new Runnable() {
    public void run() {
      GlobalScreen.setEventDispatcher(new VoidDispatchService());
    }
  });
```

**Note that non of the event consumption will work on Unix, Linux or Solaris.**
