### ISSUE TITLE
Jnativehook fires lack of events with Swing

### ISSUE THREAD

**Issue by tyrion9** [kwhat/jnativehook#262]
My Environment: Windows 10 64bit, Java 8, Swing, jnativehook 2.1.0 (newest).

I use jnativehook to listen to rfid reader, It will listen every char from 8-chars Mifare card ID. 

When I test it in console and println for 500 times, Its worked perfectly. 

Issues raises when I integrate with my Swing Desktop Application. in 100 times reading testing, there is one time jnative fires lack characters. For example: ID: 12345678, It only fires 1234568 (lack of 7).

**Comment by tyrion9** [comment]
I found this issue only ocurs when I am debugging in Netbean IDE. So, I will close this issue

**Comment by kwhat** [comment]
It happens because the java debugger blocks the event delivery thread.  There is already another bug that talks about the problem.  Basically the hook needs to be disabled when the debugger attaches, but actually implementing that maybe impossible.  I need to work on it but its not a priority right now.
