### ISSUE TITLE
Obfuscation

### ISSUE THREAD

**Issue by ghost** [kwhat/jnativehook#269]
So I have written a program and want to obfuscate it. I am currently using proguard but no matter what I do, whether I add the jnativehook library or not, it returns an error when running the obfuscated program.
Error:
`java.lang.UnsatisfiedLinkError: org.jnativehook.DefaultLibraryLocator`

**Comment by kwhat** [comment]
You cannot change the library signature or bundle the libary with your application (unless your application is GPL licenced) as it violates the LGPL license.  There are also technical reasons this is not possible, particularly because the native library needs to know the fully qualified classes to construct event objects.
