### ISSUE TITLE
Big Minecraft Sensitivity Bug!

### ISSUE THREAD

**Issue by Jochebed1337** [kwhat/jnativehook#284]
I made an external cheat for Minecraft. Please dont hate! And whenever it registeres the NativeHook my Minecraft Mouse Sensitivity speeds up and is buggy as hell. Can someone help me? My usual sensitivity is fine. But in Minecraft 1.8.x not. Except for 1.15, but that's useless.

**Comment by kwhat** [comment]
The only thing I can think of in this library that could be affecting it is some of the hacky stuff I put in to deal with things like RDP.  Set the log level to debug, and post some of the output here.  It should be pretty obvious if the library is compensating

**Comment by Jochebed1337** [comment]
Log Level to Debug? Sorry, I'm new with this library. 
Please tell me exactly what to do.

**Comment by Jochebed1337** [comment]
YAAAAAAAAAAAAAAAAAAAAAAAAAAAS !!!! I did it! I fixed it by resetting and setting the log level to OFF!! thx <3

**Comment by kwhat** [comment]
Interesting, turning of the log had a performance impact?  I certainly didn't expect that but glad you got it working.  I will look into reducing the logging for future versions by default.  Thanks for the bug report.

**Comment by kwhat** [comment]
I have gone though and done a major refactoring of the logging in the maven branch which should resolve this issue and many other complaints.  Unfortunately using maven has reached a dead end at the moment (see #290) so I am going to go back to updating the build process using Ant and hopefully we can make a release.

**Comment by ghost** [comment]
Thoughts on migrating to Gradle instead of Ant?

https://docs.gradle.org/current/userguide/migrating_from_maven.html

**Comment by kwhat** [comment]
Yes. I've _thought about it_, but after the maven and cmake fiascos, I really (really) don't want to waste more time learning another junk build system.  I think were I left off was that maven is terrible if you need to build anything outside of the default workflow and its support for building native code is not very portable and highly repetitive.  (I though ant was verbose :joy:)  So naturally I tried to build the JNI code with cmake and found out they have no replacement for pkg-config library dependencies, making library sharing between projects difficult.  So I went down the rabbit hole of cmake includes which was not a great answer due to sharing everything between the two projects, variable collisions and needing to know how the parent cmake file works. I think the better solution is to do a cmake install of the dependencies to the target build dir and leverage cmakes pkg-config to use the installed .pc file I generated via some filthy hacks in the parent project because cmake didn't include this feature?  As you can imagine I am not jumping out of my seat to try _yet-another-build-system_ that someone created to solve all of the previous failures.  Best I can tell, 40 year old tech like Makefiles work far better than their "modern" counterparts.

**Comment by kwhat** [comment]
I went though and redid the cmake integration and simplified a lot of stuff.  Things are now building in the github actions tab.

**Comment by qewer33** [comment]
I am experiencing this issue right now and my log level is already off. Any ideas?

**Comment by kwhat** [comment]
This should be resolved in 2.2, the release is on its way.  If you have more issues, please reopen or create a new bug.
