### ISSUE TITLE
Could not find keyboard map for locale 0X0000000004150415!

### ISSUE THREAD

**Issue by dladeira** [kwhat/jnativehook#285]
I am using US QWERTY Keyboard

**Comment by kwhat** [comment]
What is your current language setting?

**Comment by dladeira** [comment]
English US (windows 10)

**Comment by Tokeiito** [comment]
I have same problem on Windows 10. US English keyboard is active while testing. Also nativeKeyReleased is triggering two events on single key release.

`Mar 22, 2020 5:01:23 PM org.jnativehook.GlobalScreen$NativeHookThread enable
SEVERE: refresh_locale_list [628]: Could not find keyboard map for locale 0XFFFFFFFFF0270427!

Mar 22, 2020 5:01:23 PM org.jnativehook.GlobalScreen$NativeHookThread enable
SEVERE: refresh_locale_list [628]: Could not find keyboard map for locale 0X0000000008090809!`

**Comment by dtsw** [comment]
Happened here too, until i added logger.setUseParentHandlers(false);

**Comment by kwhat** [comment]
Please test [jnativehook-2.2-20210107.030301-37.jar](https://oss.sonatype.org/content/repositories/snapshots/com/github/kwhat/jnativehook/2.2-SNAPSHOT/jnativehook-2.2-20210107.030301-37.jar)  I have done some refactoring to the function that is probably responsible for this issue but because I cannot reproduce the problem, I need one of you to test it and let me know if it is working.  I still not know exactly why this was an issue nor why I cannot reproduce it.

**Comment by kwhat** [comment]
2.2.0 has been released and some people are reporting that this has been fixed.   If this is still a problem with the latest release, please reopen this ticket.
