### ISSUE TITLE
JNativeHook do not works when active window is running with administrator rights

### ISSUE THREAD

**Issue by peslys** [kwhat/jnativehook#296]
To repeat this bug:

1. Run NativeHookDemo on Windows 10 and make sure it hooks mouse moves and clicks.
2. Run Task Manager (or any other application using local menu "Run as administrator" menu item).
3. Select Task Manager window. 
4. While Task Manager window is selected no mouse events is handled.

 JNativeHook works as expected when it runs in application rining with administrative rights.

**Comment by kwhat** [comment]
Hey,

I suspect Microsoft is tightening up security in Windows and that there is no legitimate solution that would "fix" this.

**Comment by MrAnd3rs0n** [comment]
I would like to add it doesn't work for some program windows, like Total Commander (even running not as admin). I faced with this issue too.

**Comment by kwhat** [comment]
> I would like to add it doesn't work for some program windows, like Total Commander (even running not as admin). I faced with this issue too.

@MrAnd3rs0n I've noticed this with other application like the Terminal Services client.  There is no documentation with SetWindowsHookEx that would suggest why this is happening.  There is a ~~work-around~~ hack in the code to restart the hook if I can detect a window like this but its not the best solution.  Please open a separate bug with instructions on how to reliably duplicate your specific issue and I will take a look.

@peslys  I am able to duplicate the problem but cannot resolve the issue due to my previous comment.  You would likely need to run this library as administrator for something like that to work.
