### ISSUE TITLE
Stuck in while loop waiting for input.

### ISSUE THREAD

**Issue by ModeratelyComfortableChair** [kwhat/jnativehook#321]
This may be more related to concurrency rather than the library, but I thought I'd give here a try. There is a section of my code that is waiting for a key input. I have a global, static variable called keyWaiting. When I run this code, the "Okay, we are done" never prints. However, if I run this through debug, and step over, it will run.

In my main method
`keyWaiting = true;
while (keyWaiting);
System.out.println("Okay, we are done");`

My keyPressed method
`@Override
public void nativeKeyPressed(NativeKeyEvent nativeEvent){
if(keyWaiting){
System.out.println("You pressed a key!");
keyWaiting = false;
`

**Comment by kwhat** [comment]
Should work, I'm kind of surprised it actually works with the debugger. What dispatcher are you using?  Default?  The nativeKeyPressed callback is going to run on the same thread as the dispatcher so you probably want to synchronize the keyWaiting variable.  It's possible that it is running, but your not getting stdout from the thread.  Try the logger instead of println.

**Comment by ModeratelyComfortableChair** [comment]
So  I found the answer [here](https://stackoverflow.com/questions/34004335/do-while-loops-in-java-not-check-their-conditions-if-there-is-no-body). The explanation is that the UI thread and the main thread are not synchronized when there are no calls inside the while loop. By making keyWaiting volatile, it fixed the issue.
