### ISSUE TITLE
getKeyCode on letter and number keys returns 0 when certain application windows are focused

### ISSUE THREAD

**Issue by qewer33** [kwhat/jnativehook#322]
Hey! I was using this library for a project of mine and I realized when letter and number keys are pressed while certain programs like ms word or chrome are focused, `getKeyCode()` method returns 0 instead of the actual key number. But keys like space, backspace or esc work fine. Is this a bug or is it caused by the applications that are focused?

**Comment by kwhat** [comment]
I cannot duplicate the issue on my windows 10 system with chrome.  I suspect this may have been fixed in 2.2.2 via [this](https://github.com/kwhat/libuiohook/pull/116) PR.  Please test the [latest snapshot](https://github.com/kwhat/jnativehook/actions/runs/1967211753) and reopen this bug if the error persists.
