### ISSUE TITLE
Capturing the media play, next, and previous inputs from earbuds, headphones, speakers, etc.

### ISSUE THREAD

**Issue by nik312123** [kwhat/jnativehook#324]
Simply put, I was wondering if JNativeHook has support for media inputs from external advices such as play/pause, next, and previous.

I noticed the `NativeKeyEvent` codes `VC_MEDIA_PLAY`, `VC_MEDIA_NEXT`, and `VC_MEDIA_PREVIOUS`, which made me hopeful that what I said was the case, but it does not seem to work that way. No `NativeKeyEvents` fire at all when pressing these external buttons.

**Comment by scottismyname** [comment]
Can confirm, would be great if we could somehow capture these input events

**Comment by melloware** [comment]
@kwhat I am the author of [JIntellitype](https://github.com/melloware/jintellitype) which captures these Media Keys as well as register Global hotkeys. However it requires a Window to capture these or at least it used to when I wrote it.

However as of JDK 8u261 the JNI has stopped working.  I am not a JNI expert and was wondering if you could look at this issue? https://github.com/melloware/jintellitype/issues/30   I appreciate any insight you can offer!!!

**Comment by kwhat** [comment]
So for what it is worth, I suspect these devices (earbuds, headphones, speakers, etc) are using HID input for these keys.  They may not work with this library because of how it captures input. (See [SetWindowsHookExA](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setwindowshookexa))  

In order to interface with these devices, this library would probably need to use [Raw Input](https://docs.microsoft.com/en-us/windows/win32/inputdev/about-raw-input) which is basically just HID input.  It breaks some backward compatibility around Windows 2000 vs XP but I doubt that is an issue at this point.  I also don't think there is a way to intercept HID events for keyboards for things like preventing event propitiation.  

I've considered HID for this library in the past using [HIDAPI](https://github.com/signal11/hidapi), there may even be some tickets about it.  I just don't know enough about how HID works and there is already a number of HID solutions for Java.  I am not sure why this library would be preferred to HID for this purpose.
