### ISSUE TITLE
crash on ubuntu 14.04 64 bits

### ISSUE THREAD

**Issue by titoasty** [kwhat/jnativehook#43]
here is the error :

/usr/lib/jvm/java-7-openjdk-amd64/bin/java: symbol lookup error: /tmp/libJNativeHook-2.0.0.so: undefined symbol: hook_set_logger_proc

**Comment by kwhat** [comment]
Interesting, did you compile from source or are you using the provided binary?

**Comment by titoasty** [comment]
I used the provided binary
(and as you can see, I'm using openjdk and not oracle jdk)

**Comment by kwhat** [comment]
I can confirm the issue.  I will commit a fix this weekend and it will be included in 2.0.1 at the end of the month.

**Comment by titoasty** [comment]
oh great !
will you release a RC before the end of the month, so I can try it ?

**Comment by kwhat** [comment]
I can attach a nightly after I commit a fix ;)

**Comment by titoasty** [comment]
thanks a lot !

**Comment by kwhat** [comment]
Turned out to be a GCC 4.9 issue with LTO now using slim objects buy default.  This is awesome except binutils-ar doesn't correctly support slim-lto objects.  I am assuming this will all be fixed in the next version of binutils, but until then I will use -ffat-lto-objects to work around the issue.  See attached nightly for testing.

[JNativeHook.jar | uploaded via ZenHub](https://files.zenhub.io/54e119db0109b8b05b2e05d5)

**Comment by titoasty** [comment]
just saw that on sourceware and a patch seems already in the tube.
it's working fine now, thanks a lot !
