### ISSUE TITLE
Invalid result returned

### ISSUE THREAD

**Issue by git-xxing** [kwhat/jnativehook#439]
Hi there,

I encountered an error while using jnativehook, which says "Error: Java_com_github_kwhat_jnativehook_GlobalScreen_getPointerAccelerationThreshold [314]: Invalid result returned from hook_get_pointer_acceleration_threshold()!". I tried searching for a solution but couldn't find any relevant information. My JavaFX version is 17.0.2 and JDK version is Corretto-17.0.6.10.1. My system version is Ventura 13.2.1 (22D68) and my computer chip is Apple M1. Can someone please help me with this issue?

Thank you.

**Comment by kwhat** [comment]
> Error: Java_com_github_kwhat_jnativehook_GlobalScreen_getPointerAccelerationThreshold [314]: Invalid result returned from hook_get_pointer_acceleration_threshold()!

This just means that the library could not find a suitable source for mouse pointer acceleration threshold.  IIRC [OSX does not provide a real way to get or change this value](https://github.com/kwhat/libuiohook/blob/23acecfe207f8a8b5161bec97a8a6fd6ad0aea88/src/darwin/system_properties.c#L321).

> Can someone please help me with this issue?

This should be fixed in code already.  Solution: Use 2.2.2
