### ISSUE TITLE
Add maven artifact

### ISSUE THREAD

**Issue by tom91136** [kwhat/jnativehook#5]
It would be very nice to be able to add this library as a dependency.
(Though it seems hard since there's native code and I'm not sure how maven would handle that)

**Comment by JeromSar** [comment]
@kwhat Although this is possible, this situation is not ideal at all. I think JNativeHook should be posted on the Maven central repository.

**Comment by RaiMan** [comment]
@JeromSar and @kwhat  totally agreed, that it would be great to have it on Maven Central.

**Comment by amukas** [comment]
It is also possible to use it like a system dependency.

<dependency>
    <groupId>JNativeHook</groupId>
    <artifactId>JNativeHook</artifactId>
    <version>2.0</version>
    <scope>system</scope>
    <systemPath>${project.basedir}/lib/JNativeHook.jar</systemPath>
</dependency>

**Comment by JeromSar** [comment]
@amukas That works for compiling, but Maven Shade won't recognize the dependency and won't shade JNativeHook into the packaged jar. This is not ideal. :)

**Comment by kwhat** [comment]
So, I don't know very much about maven or how to add dependencies to it.  If someone can give me some direction on what should happen and a link to documentation on how to do it, I'll do what I can to add support for maven.

**Comment by amukas** [comment]
@JeromSar yep, you are right.
@kwhat here is one guide I've found: http://dev.solita.fi/2014/10/22/publishing-to-maven-central-repository.html, but I didn't try it by myself.

**Comment by kwhat** [comment]
Thanks for the link, I will make an attempt to add support with 2.0.1 planned for the end of Feb.

**Comment by JeromSar** [comment]
@kwhat Bump bump :)

**Comment by kwhat** [comment]
Hey, I am a bit behind with a new Apple issue in libuiohook.  It is becoming  increasingly harder to support OS X 10.5 and as soon as I figure out what to do about it, I will address this issue.

**Comment by kwhat** [comment]
I have pushed branch 2.0-maven that has an extra ant target called deploy.  Please run with `ant distclean compile deploy` and check the maven folder to verify output.  This  branch is only for testing and most of this stuff will be moved to package.xml in the cross_compile branch.  Unfortunately I can't use the maven gpg deployment and signing plugin because Gentoo doesn't support maven.

**Comment by JeromSar** [comment]
@kwhat If I remember correctly, the Central Repository requires artifacts to be signed with gpg.

**Comment by kwhat** [comment]
@JeromSar  I believe the accept gpg or pgp but I should currently be signing with gpg2.

**Comment by sixcorners** [comment]
The dependencies in that pom that gets generated will affect people depending on this project. Particularly that compile scoped dependency on jnitasks will add a transitive compile/runtime dependency to stuff downstream. For compile time dependencies people usually use either <optional>true</optional> or <scope>provided</scope>. Ant tasks seem closer to maven plugins though which don't get added as a <dependency>.

I don't know a whole lot about publishing to maven central or using ant but I know project lombok does it. They don't seem to have to list any dependencies. Maybe you don't either.

Here is a different guide: http://central.sonatype.org/pages/ossrh-guide.html It even links to instructions specifically for [apache ant](http://central.sonatype.org/pages/apache-ant.html).

By the way, if you put jnitasks into a repo you could use apache ivy to pull down that dependency instead of needing it to be downloaded manually.

**Comment by s17t** [comment]
+1 for this lib in maven central

**Comment by kwhat** [comment]
Alright, this is finally moving forward but its going very slowly.  Its taken about a week but snapshots are now available @ https://oss.sonatype.org/content/repositories/snapshots/com/1stleg/jnativehook 

As soon as I get this process down, 2.0.2 will be released here and to maven central.  If you are a maven user, please provide feedback if something is wrong or unconventional.

**Comment by kwhat** [comment]
I am all ready to stage this release on Sunday (June 28, 2015) so it will probably go live on Monday for Maven central.

**Comment by JeromSar** [comment]
Thanks much @kwhat, making jNativeHook available on Maven does improve the library's quality.

**Comment by kwhat** [comment]
Alright, its officially in central.  If there are any issues with the pom or deployment please create a new ticket. Thanks for all the help!
