### ISSUE TITLE
API to check Accessibility is enabled

### ISSUE THREAD

**Issue by kaseriya** [kwhat/jnativehook#51]
Thank you very much for this awesome library. 
Is there any way to check whether user has allowed the accessibility for the app?

When i run my app on the OS X, it asks for accessibility permission (Accessibility API is disabled!) and dialog box opens. If user does not allow accessibility, so i can display the message to allow the accessibility.  
Thanks!!

**Comment by kwhat** [comment]
Hi,

The only way to test for accessibility is to register the native hook and
see if it throws an exception.  If you get an exception, you should be able
to check the error code for accessibility.   The error codes are defined in
the NativeHookException, See
https://github.com/kwhat/jnativehook/blob/master/src/java/org/jnativehook/NativeHookException.java#L98

If you need better control of the accessibility API, you will need to
create an OSX only JNI or JNA library to handle that functionality.  Its
out of scope for this library because it only pertains to OSX.

Best Regards,
Alex

**Comment by kaseriya** [comment]
Hi,
Thanks for your quick reply,
In this case, no exception is being thrown. I see following logs

May 19, 2015 1:43:14 AM org.jnativehook.GlobalScreen$NativeHookThread enable
SEVERE: hook_run [1122]: Accessibility API is disabled!

**Comment by kwhat** [comment]
That is definitely a bug, an exception should be raised.  What version are you using?

**Comment by kaseriya** [comment]
i am using 2.0.1

**Comment by kwhat** [comment]
This should fix it.

[JNativeHook-2.0.20150523.zip | uploaded via ZenHub](https://files.zenhub.io/55615d7c1cb266657bff2c30)

**Comment by kaseriya** [comment]
It works fine now. Thanks!!

If possible then please throw some specific exception (AccessibilityException) instead of generic exception "NativeHookException" for this case.

**Comment by kwhat** [comment]
Its possible, but all of the specific exceptions would be platform dependent.  NativeHookException would still need to exist, there would just be several exception wrappers for the platform dependent items.  I was originally going to implement it that way, but I don't really see a clear benefit of having the platform dependent exceptions at the library level.  I came to that conclusion because all but two of the exception types, DARWIN_AXAPI_DISABLED and X11_RECORD_NOT_FOUND are unrecoverable.  Furthermore, the AXAPI exception is the only one that can realistically recover at run-time, but the library does not provide a facility for doing so, again because it would be highly platform specific.  I always imagined that if someone wanted to recover on OS X, the implementing application could catch the NativeHookException, check the code for DARWIN_AXAPI_DISABLED and then throw an AccessibilityException and/or ask the OS for accessibility access via JNI/JNA.  If you have a different program flow in mind, please let me know.  Many excellent suggestions have come from user feedback.

**Comment by kaseriya** [comment]
ohh my bad! I dint notice that NativeHookException has native error codes as well.
thanks!
